export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const START_REGISTER = 'START_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const START_LOGIN = 'START_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';