export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const START_REGISTER = 'START_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const START_LOGIN = 'START_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';


// manage POST
export const HOME_REFRESHING = 'HOME_REFRESHING';
export const FILL_POST_LIST = 'FILL_POST_LIST';
export const SELECT_POST_PROFILE = 'SELECT_POST_PROFILE';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const SELECT_EXPLORE_POST = 'SELECT_EXPLORE_POST';
export const INIT_EDIT_POST = 'INIT_EDIT_POST';
export const EDIT_POST_CAPTION_CHANGE = 'EDIT_POST_CAPTION_CHANGE';
export const SAVE_EDIT_POST = 'SAVE_EDIT_POST';
export const SAVE_EDIT_POST_SUCCESS = 'SAVE_EDIT_POST_SUCCESS';
export const SELECT_USER_PROFILE_HOME = 'SELECT_USER_PROFILE_HOME';
export const SELECT_USER_PROFILE_EXPLORE = 'SELECT_USER_PROFILE_EXPLORE';
export const SELECT_POST_OTHER_PROFILE_HOME = 'SELECT_POST_OTHER_PROFILE_HOME';
export const SELECT_POST_OTHER_PROFILE_EXPLORE = 'SELECT_POST_OTHER_PROFILE_EXPLORE';